spring:
  application:
    name: binflare
  profiles:
    active: dev
  jackson:
    default-property-inclusion: non_null

server:
  port: 50606

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://47.96.7.143:3609/FLARE?autoReconnect=true&failOverReadOnly=false
    username: FLARE
    password: Fight4life

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mysql://localhost:3609/FLARE?autoReconnect=true&failOverReadOnly=false
    username: FLARE
    password: Fight4life
logging:
  file:
    path: /data/${spring.application.name}/logs
  logback:
    rollingpolicy:
      max-file-size: 1GB
      max-history: 30
