spring:
  profiles:
    active: dev
  jackson:
    default-property-inclusion: non_null

server:
  port: 50606

open:
  api:
    bing:
      daily:
        image:
          url: "https://cn.bing.com/HPImageArchive.aspx?format=js&idx=0&n=1"
      base:
        url: "https://cn.bing.com"

---
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://47.96.7.143:3609/FLARE?autoReconnect=true&failOverReadOnly=false
    username: FLARE
    password: Fight4life

---
spring:
  profiles: prod
  datasource:
    url: jdbc:mysql://localhost:3609/FLARE?autoReconnect=true&failOverReadOnly=false
    username: FLARE
    password: Fight4life
