# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Deploy
        env:
          deploy_key: ${{ secrets.DEPLOY_PK }}
          deploy_host: ${{ secrets.DEPLOY_HOST }}
          deploy_user: ${{ secrets.DEPLOY_USER }}
        run: |
          SSH_PATH="$HOME/.ssh"
          REPO=binflare
          mkdir -p $SSH_PATH
          touch "$SSH_PATH/known_hosts"
          echo "$deploy_key" >> "$SSH_PATH/id_rsa"
          chmod 700 "$SSH_PATH"
          chmod 600 "$SSH_PATH/known_hosts"
          chmod 600 "$SSH_PATH/id_rsa"
          scp -r target/$REPO*.jar $deploy_user@$deploy_host:/data/tmp/$REPO.jar
          ssh-keyscan -t rsa $deploy_host >> "$SSH_PATH/known_hosts"
          ssh -o StrictHostKeyChecking=no -i $SSH_PATH/id_rsa -A -tt $deploy_user@$deploy_host sh /data/deploy_java.sh

